### ISSUE TITLE
List changing position

### ISSUE THREAD

**Issue by sunshine-ga** [salim-lachdhaf/dropdown_search#718]
**Is your feature request related to a problem? Please describe.**
While typing text in search field, list is changing its length, but also it is changing its position. It tries to align keyboard. Behaviour of jumping list on the screen is irritating.

**Describe the solution you'd like**
I would like the list to keep its first position or it should align to dropdown field.

**Additional context**
Example of different position of list:
![drowdownsearch_list](https://github.com/user-attachments/assets/5f37075a-7b2f-4813-8a53-54936f988165)

**Comment by salim-lachdhaf** [comment]
We are forced to make the menu jump up because of the keyboard. If we don't, the menu (including items, search box, etc.) will be hidden, especially if your dropdown is positioned at the bottom of the screen.

The jumping behavior depends on several parameters, such as the menu height, fit, and the vertical position of the DropdownSearch.

As mentioned by @vasilich6107, in your case (menu with a search box), it’s better to use other popup modes for an improved user experience.

If your items are limited, consider using the menu option without a searchbox.
